services:
  node:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    restart: always
    ports:
        - "80:8080"
    container_name: front
