name: Deploy
on:
  push:
    branches: [main]
jobs:
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: docs-build
      - name: Deploy on server
        id: deployment
        uses: actions/deploy-pages@v4